# Generated by Django 4.2.24 on 2025-09-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolcopal', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('enseignant', 'Enseignant'), ('parent', 'Parent'), ('directeur', 'Directeur')], default='admin', max_length=20, verbose_name='Rôle'),
        ),
    ]
