# Generated by Django 4.2.24 on 2025-09-12 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolcopal', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='sequence',
            field=models.IntegerField(blank=True, choices=[(1, 'Séquence 1'), (2, 'Séquence 2'), (3, 'Séquence 3'), (4, 'Séquence 4'), (5, 'Séquence 5'), (6, 'Séquence 6')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Format téléphone camerounais : +237XXXXXXXX', regex='^\\+237\\d{9}$')], verbose_name='Téléphone'),
        ),
    ]
